### ISSUE TITLE
Errors after editing tables

### ISSUE THREAD

**Issue by jlAlice** [splitbrain/dokuwiki-plugin-statistics#26]
I get errors after editing tables. It doesn't matter if i use the tabeledit plugin or edit a page in the edit page.

" DB Error: Table './xxxxx/stats_groups' is marked as crashed and should be repaired INSERT DELAYED INTO stats_groups (`dt`, `type`, `group`) VALUES ( NOW(), 'edit', 'admin' ),( NOW(), 'edit', 'user' ) "

xxxxx is my DB name

**Comment by splitbrain** [comment]
Your MySQL table is crashed and needs to be repaired.

**Comment by jlAlice** [comment]
Hardly, I got this error with the dokuwiki located on another  server and another DB.
And it keeps working, I get this error only if I edit tables in dokuwiki.

**Comment by splitbrain** [comment]
that error message is *very* clear. the table stats_group is marked as crashed by mysql.

**Comment by jlAlice** [comment]
Ok, thax! I cleaned stats_groups in DB. The error dos not appear.
