### ISSUE TITLE
MySQL Warning

### ISSUE THREAD

**Issue by drguildo** [splitbrain/dokuwiki-plugin-statistics#34]
Rather than just assuming that MySQL is installed, would it be possible to have some kind of check when the plugin is either installed, enabled or run?

I missed the notice on the plugin's dokuwiki.org page and was wondering why the images on my site were broken all of a sudden. Some kind of error message about MySQL being required would have been very helpful as well as maybe making the extension do nothing when it isn't present, rather than trying to execute and causing a 500 error.

**Comment by Onkh** [comment]
same problem here with some pictures. ...and after uninstall, there stay some fragments of configuration.
