### ISSUE TITLE
php 7.0

### ISSUE THREAD

**Issue by jlAlice** [splitbrain/dokuwiki-plugin-statistics#37]
Does not work in php 7.0 .

**Comment by splitbrain** [comment]
Thanks for opening the issue. Unfortunately your issue does not contain enough information. Please try to provide as much info as possible, generally following these three main questions:

* What did you do?
* What did you expect to happen?
* What happened instead?

Your issue should contain everything that might help in analyzing and reproducing the issue. That includes but isn't limited to:

* versions of the involved software
* exact error messages
* debug logs (also check your JavaScript console for web related issues)

Thanks for your help.

PS: You may want to refer to [How to Ask Questions the Smart Way](http://www.catb.org/esr/faqs/smart-questions.html) for more tips on improving your issue creation game ;-)

**Comment by jlAlice** [comment]
I can say nothing but: Dokuwiki's version is "Elenor of Tsort" and if I change my hoster's php version from 5.6 to 7.0 then the page "Access and Usage Statistics" shows nothing except for a description of the page (there is no stats)

**Comment by phl0** [comment]
I made some update to the source code. See https://github.com/splitbrain/dokuwiki-plugin-statistics/pull/38
Works on an Ubuntu 16.04 OS with PHP7
