### ISSUE TITLE
seems not working with actual dokuwiki

### ISSUE THREAD

**Issue by frank-w** [splitbrain/dokuwiki-plugin-statistics#48]
in "Frusterick Manners" no log data seems to be collected

**Comment by splitbrain** [comment]
It's working fine for me. Please provide additional info.

**Comment by frank-w** [comment]
Have you looked in my wiki? it is defined to german as main language and english as spare. In english start-page the german link-text is used...i changed de-lang-file.

Regards Frank

Am 3. Januar 2018 10:29:07 MEZ schrieb Andreas Gohr <notifications@github.com>:
>It's working fine for me. Please provide additional info.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/splitbrain/dokuwiki-plugin-statistics/issues/48#issuecomment-354968504


Mit freundlichen Grüßen
Frank Wunderlich

**Comment by splitbrain** [comment]
What? Sorry I don't follow.

**Comment by frank-w** [comment]
Sorry, i'm on wrong thread. How can i check if data is collected (where is the logfile)?

I have tried with logstats and it does not show anything

**Comment by splitbrain** [comment]
Logstats has nothing to do with this plugin. Please provide meaningful info on how to reproduce your problem. See https://www.dokuwiki.org/bugs#report_a_bug

**Comment by frank-w** [comment]
ok, the data/meta/access.log exists and got filled...don't know why the statistics took some days to show anything...currently it seems to work (statdisplay)
